[HOMEWORK-TASK-1] Added validation for note content length
vadymshukr/prjctr-test-task pull request #1
Opened 2022-01-29 10:36 UTC by vadymshukr

**WHAT?**
Implemented validation for content length in note creation and editing. If content length exceed 1000 characters, user can not create or edit note, because Save button become disabled. 
Also refactor some useState hooks to useMemo for optimization.

**HOW?**
1. Create new counter variable for detecting how many characters already typed and how many left.
2. Refactor way how disabling save button works. Now I use useMemo hook, where i check all requirements for making button disabled/enabled

**WHY**
I used useMemo hook for content length counter for better optimization. For same reason refactor some old code.

2022-01-29 12:31 UTC, maxzag commented on src/components/create-note/create-note.tsx
> +        return !contentValue.length || !titleValue.length || titleValue.length > maxTitleLength || sanitizeHtml(contentValue, {allowedTags: []}).length > maxContentLength
В titleCounter ты делаешь sanitizeHtml, а здесь нет. Лучше привести все к одному виду, вынести в одну переменную валидации (с использованием useMemo) и переиспользовать.

2022-01-29 12:40 UTC, maxzag requested changes

2022-01-29 12:40 UTC, maxzag commented on src/components/create-note/create-note.tsx
> +    const isSaveButtonDisabled = useMemo(() => {
В titleCounter ты делаешь sanitizeHtml, а здесь нет. Лучше привести все к одному виду, вынести в одну переменную валидации (с использованием useMemo) и переиспользовать.

2022-01-29 18:15 UTC, maxzag approved these changes

2022-01-30 15:11 UTC, Rastopyr approved these changes

2022-01-30 15:11 UTC, Rastopyr commented on src/components/create-note/create-note.tsx
>                      onChange={(e) => {handleTitleLength(e)}}
nit: `e => handleTitleLength(e)`

2022-01-31 10:35 UTC, merged